//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W26102021
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICI
    {
        public long ID { get; set; }
        public string KADI { get; set; }
        public string SIFRE { get; set; }
    }
}
