//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W19102021
{
    using System;
    using System.Collections.Generic;
    
    public partial class KISI
    {
        public long Id { get; set; }
        public string ADI { get; set; }
        public string SOYADI { get; set; }
    }
}
